name: iotsupperapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dropdown_button2: ^1.4.0
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  provider: ^6.0.2


  cupertino_icons: ^1.0.3
  sizer: ^2.0.15
  get: ^4.3.8
  permission_handler:
  dio: ^4.0.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # mqtt_client: ^9.6.6
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  connectivity_plus: ^2.3.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.13
  mime_type: ^1.0.0
  chewie: ^1.3.2
  # video_player: ^2.4.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.1.0
  device_info_plus: ^3.2.3
  # firebase_auth: ^3.3.18
  # firebase_core: ^1.17.0
  crypto: ^3.0.1
  flutter_easyloading: ^3.0.3
  encrypt: ^5.0.1
  sqflite: ^2.0.0+3
  # firebase_messaging: ^11.4.0
  json_path: ^0.3.1
  url_launcher: ^6.1.3
  mqtt_client: ^9.8.1
  emoji_flag_converter: 1.1.0
  intl: 0.17.0
  easy_debounce: 2.0.1
  

  cached_network_image: 3.1.0+1
  page_transition: 2.0.4
  percent_indicator: 4.0.0
  
  timeago: 3.1.0

  flutter_switch: ^0.3.2
  firebase_core: ^2.1.1
  file: ^6.1.4
  qr_flutter: ^4.0.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.6


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/resources/
    - lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
