// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHsRRZpDIccnXR2EE9-wX8nRytFfCNcA',
    appId: '1:1085844096653:web:e7569fb5b618394a1404c4',
    messagingSenderId: '1085844096653',
    projectId: 'iot-evergreen',
    authDomain: 'iot-evergreen.firebaseapp.com',
    storageBucket: 'iot-evergreen.appspot.com',
    measurementId: 'G-7MFRYCD5FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG0ZGEjiSNrIG22SZoEkl9Yfa4Ach5n2M',
    appId: '1:1085844096653:android:dba88ab84880e2021404c4',
    messagingSenderId: '1085844096653',
    projectId: 'iot-evergreen',
    storageBucket: 'iot-evergreen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMu94m5UkXvrYfRGhze4RjBzDmiNshypM',
    appId: '1:1085844096653:ios:00d7997d9e2c7a301404c4',
    messagingSenderId: '1085844096653',
    projectId: 'iot-evergreen',
    storageBucket: 'iot-evergreen.appspot.com',
    iosClientId:
        '1085844096653-pg7u8hpuj369unpdaj9t7c76m02vqc0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.dkccMobileApp',
  );
}
